version: '2'
services:
    myapp:
        build: ./app
        container_name: "myapp"
        volumes:
            - /app
        ports:
            - 8080:8080
        links:
            - mongodb
        depends_on:
            - mongodb
        restart: always
    mongodb:
        build: ./data
        container_name: "mongodb"
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null # --quiet
        restart: unless-stopped
